### ISSUE TITLE
Internal variable conflict $__from and $__to

### ISSUE THREAD

**Issue by rerime** [grafana/azure-monitor-datasource#100]
Grafana has two built in time range variables in $__from and $__to. They are currently always interpolated as epoch milliseconds. These variables are only available in Grafana v6.0 and above.

https://github.com/grafana/azure-monitor-datasource#azure-log-analytics-builtin-variables
http://docs.grafana.org/reference/templating/#the-interval-variable

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

This is being fixed now and will be released in Grafana 6.3: https://github.com/grafana/grafana/pull/17140
