### ISSUE TITLE
Metric query has only auto and 1m time grains

### ISSUE THREAD

**Issue by lemillermicrosoft** [grafana/azure-monitor-datasource#105]
No matter the time range of the dashboard, the Azure Monitor metric graph panels only have options of auto (which defaults to 1m) or 1m. Do I need to do something to enable custom values or fix auto behavior?

![image](https://user-images.githubusercontent.com/35783676/57085142-79803500-6cb0-11e9-85a2-a02a21f3e0c0.png)

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

The list of time grains is specific to the metric and in this case 1m is the only supported time grain for the Microsoft.ContainerService/managedClusters namespace. This is what the API returns - just one time grain:

![image](https://user-images.githubusercontent.com/434655/58163030-8a0a4680-7c83-11e9-945b-ad2b3e801df0.png)
 
If this is a bug then it is a bug in the Azure Monitor API and not in the datasource.
