### ISSUE TITLE
Issue with building package

### ISSUE THREAD

**Issue by nhjiejan** [grafana/azure-monitor-datasource#106]
When i try to build a custom plugin i get the following error:

```
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
```

I'm following the instructions as specified in the Development section in the readme.

Any help would be greatly appreciated.

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

This repo was updated to webpack before porting and the build instructions are out of date.
