### ISSUE TITLE
Support Azure Germany

### ISSUE THREAD

**Issue by ThisWillDoIt** [grafana/azure-monitor-datasource#12]
Currently there is no way of connecting an Azure Monitor that is not hosted in the "normal" Azure cloud but for example in Azure Germany.  
It would be nice if the Azure variant could be selected when adding a data source with this plugin.

**Comment by daniellee** [comment]
Is that possible via the Azure portal? Any docs you could point me to on how that works?

**Comment by ThisWillDoIt** [comment]
Well unfortunately the documentation about Azure Germany is very limited. But the fact the portal shows the Azure Monitor tab make me wish that the API works too.  
I couldn't find any documentation on that part, but for most other services the API endpoints just change from:
*.blob.core.windows.net       ------>      *.blob.core.cloudapi.de
*.database.windows.net        ------>      *.database.cloudapi.de
*.redis.cache.windows.net    ------->     *.redis.cache.cloudapi.de

etc. so It might be just a chance in the endpoint URL for the monitor too.
I might be able to try it out with my Azure Germany account on Sunday, but I don't know much about Grafana, writing plugins etc, so I don't feel that confident about writing a full merge request if the new endpoint works.
