### ISSUE TITLE
Dimension as variable

### ISSUE THREAD

**Issue by mazhead** [grafana/azure-monitor-datasource#125]
Hello,
is there any possibility to have dimension as a variable?
This would be useful when filtering out for example scale sets or selecting a specific disk.

I did not find any documentation on this and testing out did not bring any results.

**Comment by florianrusch** [comment]
@mazhead Hi, have you already found a solution?

**Comment by mazhead** [comment]
> @mazhead Hi, have you already found a solution?

nope, neither any answer here

**Comment by papagian** [comment]
This repository is deprecated since the Azure Monitor datasource is included in core grafana.
So yes, the right place to post issues for the Azure Monitor datasource is https://github.com/grafana/grafana.
