### ISSUE TITLE
Application Insights Users/Count and Sessions/Count not returning data

### ISSUE THREAD

**Issue by robertholz** [grafana/azure-monitor-datasource#13]
Every time I try to make a graph with the Users/Count value (with the unique arrogation), I cannot return any data, it just returns NaN. I have attached a screenshot of what I am trying to configure

![screenshot_1](https://user-images.githubusercontent.com/25103587/32442825-a2e362d0-c2f4-11e7-975f-be2fef764887.png)

**Comment by daniellee** [comment]
Thanks for reporting this. Unique is missing from the list of allowed aggregations. Will add it and get a release out.

**Comment by daniellee** [comment]
@robertholz there is a new version of the plugin with this fix.
