### ISSUE TITLE
Filtering on Column Values

### ISSUE THREAD

**Issue by Christoffleroux** [grafana/azure-monitor-datasource#14]
Nice plugin, thanks

Just one question.  Is it possible to filter on the data being displayed similiar to the following query.

requests
| where (itemType == 'request')
| where name  startswith "GET /SomePath" or name contains "SomeValue"

**Comment by daniellee** [comment]
Do you mean support the [Application Insights query API](https://dev.applicationinsights.io/documentation/Using-the-API/Query)? 

That is not currently supported (as it is a totally different API to the metrics API) and not in the plans for the near future. Filtering metric queries with OData filter expressions is higher up the list of priorities.

**Comment by Christoffleroux** [comment]
That will be perfect, thanks allot.

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

Support for Application Insights Analytics is implemented already.
