### ISSUE TITLE
Metrics tab hidden

### ISSUE THREAD

**Issue by rmmartins** [grafana/azure-monitor-datasource#16]
I installed Graphana folowing this link http://docs.grafana.org/installation/debian/ and then I installed the Azure plugin with this tutorial: https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-send-to-grafana.

After installs, the metrics tab is hidden. Anyone with the same issue?

![graphana](https://user-images.githubusercontent.com/387116/32744229-f9be956a-c895-11e7-8821-a844c3d5d089.png)

**Comment by daniellee** [comment]
You are looking at the dashboard settings. You need to open the panel settings: click on the "Panel Title" to get a context menu and choose edit.

**Comment by daniellee** [comment]
Closing this but I can reopen if you need more help.

**Comment by rmmartins** [comment]
Ok, thank you and sorry for my mess. Now it's working:

![image](https://user-images.githubusercontent.com/387116/32946524-03f40cd6-cb7f-11e7-8b72-5beaa7887035.png)

**Comment by daniellee** [comment]
Great!
