### ISSUE TITLE
Allow Use of Templating Variables in Queries

### ISSUE THREAD

**Issue by Smuggla** [grafana/azure-monitor-datasource#17]
I am using Prometheus' Azure Service Discovery to create template variables for Azure monitor queries, but I am unable to add them to my queries.

Currently have it setup:
```
$subscription | grafana-azure-monitor-datasource
$resourcegroup | label_values(up{job="$subscription"}, resource_group)
$host | label_values(up{resource_group="$resourcegroup"}, instance
```

Would be great to add this template functionality!

Thanks!

**Comment by daniellee** [comment]
Why can you not add them to your queries?

Just to be certain of the details: you have template variables that are of type "Query" and "Data source" set to Prometheus and you want to use these template variables in an Azure Monitor query?

Here is an example of an Azure Monitor query with a template variable named $rg:

![image](https://user-images.githubusercontent.com/434655/32804363-1ded1a1e-c987-11e7-811d-191d1c898771.png)

**Comment by daniellee** [comment]
@Smuggla did you get this working?

**Comment by Smuggla** [comment]
Sorry I did, I was just expecting it to be there automatically. Works Great!

I appreciate you setting me straight! 

Thanks for everyone's hard work!
