### ISSUE TITLE
Application Insights: Bad Request: MissingApiVersionParameter when Grafana version is < 4.6

### ISSUE THREAD

**Issue by marchenko-devpro** [grafana/azure-monitor-datasource#20]
Hi there,

I was trying to configure Application Insights Details, but faced the issue below:

Error
1. Application Insights: Bad Request: MissingApiVersionParameter. The api-version query parameter (?api-version=) is required for all requests.

Could you please help me to figure it out?

**Comment by daniellee** [comment]
Can you give some more details, please. 

When do you get this error? Is when you are pressing the "Save and Test" button on the data source config page?

**Comment by enutrofff** [comment]
Hi All, 

I have the same issue. When I'm pressing the "Save and Test" button on the data source config page

![image](https://user-images.githubusercontent.com/4835211/33165806-d111ad8e-d040-11e7-949a-5a5a4ba35d56.png)

Grafana v4.3.2 (commit: ed4d170)

Grafana data source for Azure Monitor/Application Insights version 0.0.9

**Comment by enutrofff** [comment]
Update:

It works with Grafana v4.6.2 (commit: 8db5f08)

**Comment by marchenko-devpro** [comment]
Works for me too. Thanks.

**Comment by daniellee** [comment]
I should add a version check and show a better error.

**Comment by marchenko-devpro** [comment]
Thanks, Daniel. It would be helpful.
BTW, your plugin is great.
