### ISSUE TITLE
1. Azure Monitor: Unauthorized: AuthenticationFailedMissingToken. Authentication failed. The 'Authorization' header is missing the access token. 

### ISSUE THREAD

**Issue by mpender** [grafana/azure-monitor-datasource#21]
Grafana Server 4.6.2 (update from 4.4.1)

Using the latest Azure monitor plugin )

Client/tenant/client-secret/sub-id are all correct and working for other applications.

**Comment by daniellee** [comment]
Are there any errors in the Grafana server log? 

This error usually means that either the tenant id, client id or client secret is incorrect. These three are needed to fetch a token from the Azure Monitor API. 

Does the Grafana server have access to Azure? The token authentication is done on the Grafana server backend.

(Need to improve that error message though).

**Comment by daniellee** [comment]
Looked at the error checking to try and get a better error message. It is going to require a change to Grafana so I will see if I can get that into the next release.

**Comment by mpender** [comment]
thanks for the swift responses :) 

I checked out the logs doing another 'save & test' 

t=2017-11-27T09:49:23+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname="$user" method=GET path=/api/datasources/proxy/2/azuremonitor/subscriptions/$subscriptionid/resourceGroups status=401 remote_addr=$remote_azure_endpoint_ip time_ms=1083 size=144 referer=https://mygrafana/datasources/edit/2
t=2017-11-27T09:49:24+0000 lvl=info msg="Got new access token" logger=data-proxy-log ExpiresOn=1970-01-01T00:00:00+0000
t=2017-11-27T09:49:24+0000 lvl=info msg=Requesting logger=data-proxy-log url="https://management.azure.com/subscriptions/$subscriptionid/resourceGroups?api-version=2017-06-01"
t=2017-11-27T09:49:25+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname="$user" method=GET path=/api/datasources/proxy/2/azuremonitor/subscriptions/$subscriptionid/resourceGroups status=401 remote_addr=$remote_azure_endpoint_ip time_ms=1072 size=144 referer=https://mygrafana/datasources/edit/2
t=2017-11-27T09:49:26+0000 lvl=info msg="Got new access token" logger=data-proxy-log ExpiresOn=1970-01-01T00:00:00+0000
t=2017-11-27T09:49:26+0000 lvl=info msg=Requesting logger=data-proxy-log url="https://management.azure.com/subscriptions/$subscriptionid/resourceGroups?api-version=2017-06-01"
t=2017-11-27T09:49:27+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname="$user" method=GET path=/api/datasources/proxy/2/azuremonitor/subscriptions/$subscriptionid/resourceGroups status=401 remote_addr=$remote_azure_endpoint_ip time_ms=1037 size=144 referer=https://mygrafana/datasources/edit/2

This smells like an azure permissions type issue...

**Comment by daniellee** [comment]
Unfortunately, you will not be able to see the actual cause but it is a 401 which means that the problem is with the client and client secret or azure permissions as you noted.

I had a problem after changing subscription and the only way to get a working client/service principal was to create it with the azure cli. I could not get it to work via the portal. Something like this:

`az ad sp create-for-rbac -n "http://localhost:3000"`

https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest

**Comment by mpender** [comment]
Thanks for the update, will try it out but I think we can close this ticket
