### ISSUE TITLE
Issue with different time grain settings

### ISSUE THREAD

**Issue by adoelger** [grafana/azure-monitor-datasource#22]
I track custom events to application insights (with 2 attributes). I want to display the events total grouped by one of the attributes in a table panel (table transform = time series aggregation). When time grain is set to 1 minute the total is missing some events - compared to a query in azure insights analytics. When i set the the time grain to 1 day the total is the same as in analytics, but some of the grouped items missing in the table.

**Comment by daniellee** [comment]
Can you show an example of this data from two short periods from the this plugin and from the Azure Monitor portal? Are the events missing at the start or end of a timerange? 

Is the query the same? You can see the raw query sent to the App Insights api by using the query inspector on the Metrics Tab.

**Comment by adoelger** [comment]
It seems the Azure API returns different results for timeGrain 1m vs 1h:

[timeGrain1h.txt](https://github.com/grafana/azure-monitor-datasource/files/1530987/timeGrain1h.txt)
[timeGrain1m.txt](https://github.com/grafana/azure-monitor-datasource/files/1530988/timeGrain1m.txt)

SA05 -> 1 event is missing in timeGrain 1h.

**Comment by daniellee** [comment]
Thanks that was exactly what I needed. Will investigate.

**Comment by daniellee** [comment]
This repo is going to be archived. The Azure Monitor plugin was moved into the Grafana repository for version 6.0 of Grafana. If you are using Grafana 6.x then you will automatically start using the built-in version of the Azure Monitor datasource.

Announcement: https://grafana.com/blog/2019/02/25/grafana-v6.0-released/#azure-monitor-datasource
Documentation for Azure Monitor in Grafana: https://grafana.com/docs/features/datasources/azuremonitor/

Please open a new issue in the Grafana repo if this is still an issue.
