### ISSUE TITLE
Support for Azure Gov

### ISSUE THREAD

**Issue by wsw-bedwards** [grafana/azure-monitor-datasource#23]
Please add support for Azure Gov, I'm getting the current error testing/saving up the data source:

Azure Monitor: Not Found: SubscriptionNotFound. The subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found.

**Comment by daniellee** [comment]
Do you mean this: https://azure.microsoft.com/en-us/overview/clouds/government/

Microsoft said they are looking into add support for the various sovereign clouds to the Azure Monitor API (Azure Germany, Government etc.) but basically the endpoints for these sovereign clouds are different right now.

This issue is nearly the same as: #12

**Comment by wsw-bedwards** [comment]
Yes, that is correct.  The endpoints for Gov are *.us instead of .com

**Comment by hoopty** [comment]
Correction, the api endpoint is management.usgovcloudapi.net.

**Comment by wsw-bedwards** [comment]
To help diagnose - I manually updated the endpoint to see if it might be an easy fix, and I then got the following error:
`1. Azure Monitor: Unauthorized: AuthenticationFailedMissingToken. Authentication failed. The 'Authorization' header is missing the access token.`

**Comment by kangxhwork** [comment]
it works great with normal Azure. But for Azure hosted in China with different API endpoint, data source cannot be added with authentication error.

**Comment by catweisun** [comment]
It's better to support customized the Azure Monitor endpoint to support different Azure instance such as Azure sovereign cloud or Azure stack in future. The endpoint could be one of the configuration items like sbuscription id, tenant id, client id and client secret.

**Comment by DONGZHUPENG** [comment]
+1 catweisun's comment
