### ISSUE TITLE
Not all the Namespace and metrics are listing in grafana

### ISSUE THREAD

**Issue by gowrisankar22** [grafana/azure-monitor-datasource#25]
Hello Colleagues,

I have added the azure-monitor plugin into my existing grafana. After adding Azure Monitor API Details into data source, when i try to create dashboard it lists only below Namespaces.

Microsoft.Compute/availability-sets
Microsoft.Compute/disks

Also metrics are not listed from the drop down.

how to bring all the Namespace and metrics ?? do we need to set any configuration in azure portal ?

**Comment by asheniam** [comment]
It looks like the existing Azure Monitor plugin hardcodes the list of supported Azure resource types so it will require some code update to add new supported Azure resource types.  When I was experimenting with it though, even if the Azure resource type doesn't show up in the drop down, if you know the name of the Azure resource type and type it in, the plugin will still work.

Wrt Microsoft.Compute/availability-sets and Microsoft.Compute/disks, there are no supported metrics for these resource types.  Take a look at the following docs:

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics

**Comment by gowrisankar22** [comment]
@asheniam thanks a lot for your input. We are currently looking for the all quotas to bring on top of grafana using this plugin. could you please help get this done. ?

**Comment by daniellee** [comment]
Microsoft gave me a list of API's that should be included. I will ask them for an updated list. Maybe the list in #31 is what I need.

**Comment by daniellee** [comment]
Closing this as Azure Monitor does not provide metrics for Microsoft.Compute/availability-sets and
Microsoft.Compute/disks which means this plugin can't fetch them.
