### ISSUE TITLE
No metrics for WebApps slots

### ISSUE THREAD

**Issue by gothvf** [grafana/azure-monitor-datasource#27]
If you use webapps slots the metrics are not pulled (only the webapp is)

**Comment by gothvf** [comment]
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/7/azuremonitor/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxx/providers/Microsoft.Web/sites/slots/xxxxxxxxxxxxxxxxxxx/xxxxxxx/providers/microsoft.insights/metricdefinitions?api-version=2017-05-01-preview"
response:Object
error:Object
code:"ResourceNotFound"
message:"The Resource 'Microsoft.Web/sites/slots' under resource group 'xxxxxxxxxxxxxxxxxxxxx' was not found."

**Comment by nikos9742** [comment]
Hi, 
I'm very interested in solving that issue, if people can spend some time on IRC or Slack or email or whatever explaining me where i need to look to find how to solve the issue. I already know how to get the metric definitions for webapp slots in the Azure Monitor API and i think with some patching for that special cases we can solve that issue.

Who's with me on that ? @villekr ? @daniellee

**Comment by nikos9742** [comment]
The correct request should be : https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Web/sites/xxxxxxxxxxxxxxxxxxxxxx/slots/slotname/metricdefinitions?api-version=2016-08-01

**Comment by nikos9742** [comment]
There is a PR #45 that solve this issue. Can you merge it to master ? @daniellee Thanks a lot

**Comment by DeV1L** [comment]
Still not works
`[root@zbx-01 ~]# grafana-cli plugins ls | grep azure
grafana-azure-monitor-datasource @ 0.1.1
`
![image](https://user-images.githubusercontent.com/8911626/38094105-8fba3994-3375-11e8-9b00-fe57336b0c94.png)

**Comment by daniellee** [comment]
This fix is released in version 0.1.2.
