### ISSUE TITLE
List of supported metric namespaces in AzureMonitorQueryBuilder needs to be updated

### ISSUE THREAD

**Issue by asheniam** [grafana/azure-monitor-datasource#31]
The list of supported metric namespaces in AzureMonitorQueryBuilder needs to be updated to match the following doc:

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics

For example, Microsoft.Insights/autoscalesettings is not in the list of supported metric namespaces.

Additionally I wonder if we should whitelist specific Azure resource types and not entire Azure resource provider namespace.  For example, 'Microsoft.Compute' is listed in the supported namespace but should it instead be added as 'Microsoft.Compute/virtualmachines' and 'Microsoft.Compute/virtualmachinescalesets'?  If you add 'Microsoft.Compute', it brings in other resource types under that namespace in the drop down but they won't have any metrics.

**Comment by gowrisankar22** [comment]
#25 
+1
We are currently looking for the all quotas to bring on top of grafana using this plugin. could you please help get this done. ?

**Comment by asheniam** [comment]
When you say 'all quotas', can you be more specific on what you are referring to?

**Comment by gowrisankar22** [comment]
Monitor per subscription quotas and usage.
![capture1](https://user-images.githubusercontent.com/20590107/35423521-228201c2-0274-11e8-822a-b91d59807a37.PNG)

**Comment by asheniam** [comment]
Unfortunately this data isn't available via Azure Monitor as a metric but I agree it would be nice to see this info exposed in Grafana.

**Comment by daniellee** [comment]
Closed by 5dd6d8cbdf46b0304b9d2d1bbf35f7eefe86abc1

Added the following namespaces to the whitelist:

- Microsoft.DataFactory/datafactories
- Microsoft.DataFactory/factories
- Microsoft.KeyVaults/vaults
- Microsoft.LocationBasedServices/accounts
- Microsoft.PowerBIDedicated/capacities
- Microsoft.Relay/namespaces
