### ISSUE TITLE
Add support for Azure Monitor Log Analytics

### ISSUE THREAD

**Issue by daniellee** [grafana/azure-monitor-datasource#56]
- [x] Integrate the Monaco editor
- [x] Integrate the KustoDB Language Service to get intellisense
- [x] Add a new option for Log Analytics and integrate the [Log Analytics API](https://portal.loganalytics.io/demo)
- [x] Support parsing the data into time series format
- [x] Support parsing the data into table format
- [x] Documentation
- [x] Support switching Workspace in the query editor
- [x] Have Run button like the analytics portal has
- [x] Show the raw query after executing
- [x] Slim down the Monaco editor js file by removing unneeded features (currently 8MB uncompressed)
- [x] Use the /metadata endpoint to get the schema (/query/schema will be deprecated) and for multiple databases/solutions put into one virtual database for the intellisense schema.
- [x] Investigate which AAD role is needed and document it.
- [x] Improve Intellisense for Grafana macros - getting double entries in the list sometimes.
- [x] Template variable support
- [x] Annotation support
- [x] Handle Esc button when in monaco editor.
- [ ] Support for Azure Gov
- [x] Monaco Code Editor refactoring
- [ ] Add throttling support when autorefreshing (use the API to find out when requests are throttled and wait for the retry-after period)
- [x] Add message that it requires Grafana 5.3.

**Comment by daniellee** [comment]
This is done except for: 

- Going to test it with multiple workspaces
- Documentation for template variables and annotations.

**Comment by cfarre** [comment]
can you tell me if log analytics support in grafana is currently available or only azure monitor resources and application insights? any estimate when is going to be ready?

**Comment by daniellee** [comment]
@cfarre log analytics support is not available yet - I am waiting for the green light from Microsoft's legal department on an open source License for a Kusto component (Kusto is the database used by log analytics). 

So I have no idea how long that will take but hopefully soon as they are starting to test a preview version with some customers this week.

**Comment by fernandrez** [comment]
Hello, thank you very much for Grafana! Let me please ask: can we use log analytics queries directly to define the chart legends in terms of resource tags for example? is there an alternate way to achieve this?

**Comment by cconrado** [comment]
Is this live ?

**Comment by daniellee** [comment]
@cconrado hopefully this week - the license issue is now resolved.

**Comment by samhodgkinson** [comment]
Any update on when this will be publicly available?

**Comment by daniellee** [comment]
This is now published with the Azure Log Analytics support marked as being in preview.

**Comment by cfarre** [comment]
@daniellee 
we are doing a project based on log analytics and grafana. do you know when this will be publicly available?

**Comment by daniellee** [comment]
@cfarre it is already publicly available. Support is included in the latest release.

**Comment by cfarre** [comment]
@daniellee can you send me install instructions. I cannot find any doc from MS. I followed manual instructions in https://github.com/grafana/azure-monitor-datasource/blob/master/README.md we tested this release and are having performance issues, plus other function problems.

**Comment by cfarre** [comment]
@daniellee this is the problem I am facing. Any query I am running it hangs the UI in grafana to the point is unresponsive. The queries run correctly on azure portal

this is the simple query we are testing going back 30 minutes. what is the best channel to discuss those issues? is there something we are doing incorrectly?

SparkMetric_CL 
| where name_s contains "driver.DAGScheduler.job.allJobs"

**Comment by JamesHealey94** [comment]
> @daniellee this is the problem I am facing. Any query I am running it hangs the UI in grafana to the point is unresponsive. The queries run correctly on azure portal
> 
> this is the simple query we are testing going back 30 minutes. what is the best channel to discuss those issues? is there something we are doing incorrectly?
> 
> SparkMetric_CL
> | where name_s contains "driver.DAGScheduler.job.allJobs"

You may need a filter on timestamp.
| where $__timeFilter()
will use the time range selected in grafana

**Comment by daniellee** [comment]
@cfarre the portal automatically adds a time filter clause to any query which Grafana does not so @JamesHealey94 is correct you should always add a time filter.

**Comment by cfarre** [comment]
@daniellee @JamesHealey94 
Ok I fixed this issue. now I have another question. we have multi variables template and we are trying to use $__escapeMulti($myVar) or $__contains(colName, $myVar) but the macros do not work on our grafana

**Comment by daniellee** [comment]
@cfarre could you provide some more information?

What does the raw query look like? And what does your template variable definition look like?

**Comment by tjmoore** [comment]
@cfarre - don't know if it's your issue, but I've got a problem with $__contains macro, which I've raised in #84

**Comment by cfarre** [comment]
@daniellee 
we have developed a dashboard to monitor spark clusters. Below is one of our queries. Is it possible to parameterize the SparkListenerEvent_CL? additionally can you point me to deployment automation of grafana and dasboards? I would like to automate a deployment script that installs grafana, sets up the datasource and installs the dashboards.

SparkListenerEvent_CL
| where $__timeFilter(TimeGenerated)
| where Event_s contains "queryprogressevent"
| extend sname=strcat(progress_name_s,"-","triggerexecution") 
| summarize percentile(progress_durationMs_triggerExecution_d,90)  by bin(progress_timestamp_t, 1m), sname
| order by  progress_timestamp_t  asc  nulls last

**Comment by cfarre** [comment]
@daniellee @JamesHealey94 
I need to share a dashboard with many deployments for customers. One problem we are having is that the workspace name does not accept variables. I was thinking to write a bash script to replace workspace name but it looks like it is replaced with a guid. how can we support this scenario where we have to share the json file dashboard sthat will run in different workspaces? replacing them manually seems the only way to do it. this will be for spark community and I ask you to give me some advice here.

  "workspace": "6cdabfff-ca67-46d4-a18c-8e5b2d81b6bf"

**Comment by cfarre** [comment]
@daniellee @JamesHealey94 
I realize that the guid is actually the workspaceId. we will give a script that replaces that entry with customers workspaceId. I would like to ask a request for the workspace entry be a variable that we could replace easily
