### ISSUE TITLE
Azure Monitor 0.2.0 is not published at grafana plugins

### ISSUE THREAD

**Issue by patrykpiotrmarek** [grafana/azure-monitor-datasource#62]
Please, publish 0.2.0 version of Azure Monitor plugin at https://grafana.com/plugins because i want to use it within docker container and the latest available version is 0.1.1 (https://grafana.com/plugins/grafana-azure-monitor-datasource). Therefore, I can not take advantage of the latest functionality using docker.

**Comment by daniellee** [comment]
Sorry, I can’t just yet. Waiting on Microsoft legal to approve some things first.

**Comment by olsonnn** [comment]
any news on this? looking forward to it!

**Comment by daniellee** [comment]
This has been published since a few weeks ago.
