### ISSUE TITLE
Install datasource on xyz.grafana.net

### ISSUE THREAD

**Issue by libardo** [grafana/azure-monitor-datasource#67]
Since last week the Azure data source seems to be missing. The dashboard show only sample data and the data source config displays the error "Plugin not found, no installed plugin with that id".

Any ideas?

**Comment by aabiryukov** [comment]
I had the same problem in cloud Grafana since last week (occurred twice).
Workaround to fix: remove the plug-in (Azure Monitor Data Source) and install it again.

**Comment by daniellee** [comment]
Will ask our GrafanaCloud team. I know we updated all the instances last week due to the security patch fix but it should not have removed plugins.

**Comment by replay** [comment]
Thanks for the report @libardo and @aabiryukov .
Could you give me the names of your instances, please? Then I'll investigate what happened.

**Comment by aabiryukov** [comment]
@replay I sent the name of instance to your e-mail.

**Comment by daniellee** [comment]
@aabiryukov do you remember what day this error first occurred?

**Comment by aabiryukov** [comment]
@daniellee first on August 29, second on August 31.

**Comment by daniellee** [comment]
The root cause of the problem is that the Grafana instance failed to download the plugins before starting the Grafana server. If you restart the instance (which you can trigger by adding, updating or removing a plugin) then it should work. Thanks for bringing this to our attention - we will try and fix the root cause as soon as possible.

**Comment by daniellee** [comment]
Actually think we found it: https://github.com/grafana/grafana/issues/13079

This fix will be coming out in the next release of Grafana which GrafanaCloud instances will get on the same day (or day after) the release.

**Comment by geetuvaddeboina** [comment]
facing the same issue can anyone help me out

[root@localhost yum.repos.d]# grafana-cli plugins install snuids-radar-panel
installing snuids-radar-panel @ 1.4.1
from url: https://grafana.com/api/plugins/snuids-radar-panel/versions/1.4.1/download
into: /var/lib/grafana/plugins

Failed downloading. Will retry once.
Failed downloading. Will retry once.

Error: ✗ Corrupt http response from source. Please try again.

**Comment by daniellee** [comment]
@geetuvaddeboina we are doing a beta release of Grafana with a fix for this. If you just try again it should work (you might have to try again twice).

**Comment by geetuvaddeboina** [comment]
Thanks.It's working fine now  :)
