### ISSUE TITLE
Azure Log Analytics using just App Id and API key

### ISSUE THREAD

**Issue by JamesHealey94** [grafana/azure-monitor-datasource#72]
Currently it seems Azure Log Analytics requires a subscription id, tenant id, client key and client secret.

![image](https://user-images.githubusercontent.com/633125/47802371-05c49600-dd28-11e8-8a85-374e4b24c0e4.png)

I'd prefer not to have to set up a Log Analytics workspace and service principal if possible.

It should be possible to get this data using just a an app ID and API key; see API explorer here for GET /query : https://dev.applicationinsights.io/apiexplorer/query

**Comment by JamesHealey94** [comment]
I didn't realise custom Kusto queries are now supported with Application Insights. This solves my needs.

**Comment by daniellee** [comment]
@JamesHealey94 that authentication method is not recommended and is only used for demo purposes which is why it is not supported in this plugin.

**Comment by JamesHealey94** [comment]
@daniellee 

https://dev.applicationinsights.io/documentation/Overview/URL-formats

> Unless you area already using Azure Active Directory, the recommendation is to use the Public API format and authenticate with an API key.

Am I missing something here? It seems like the API key is the recommended authentication method.

**Comment by daniellee** [comment]
@JamesHealey94 I meant for Azure Log Analytics - this came up when I asked Microsoft about how authentication should be implemented. 

But you are talking about App Insights Log Analytics? (Super confusing with the similar names for all the services). 

I haven't been talking to Microsoft about that, as support came via a PR. So maybe we could add support for that but as App Insights will eventually be rolled into Azure Monitor, I'm not sure if it is worth leading users down the wrong path. It is more secure to use token authentication.
