### ISSUE TITLE
Azure Monitor: Not Found: MissingSubscription

### ISSUE THREAD

**Issue by aquiros17** [grafana/azure-monitor-datasource#8]
Hi everybody,

We have an error with the plugin Azure Monitor for Grafana. When I try to configure the Datasource on Grafana, I put all the required fields and I receive the error Azure Monitor: Not Found: MissingSubscription.

If I try to login via powershell with the app credentials (App ID and Key), I login succesfully and I can see the subscription.

Any ideas? 

Any help will be appreciated

**Comment by aquiros17** [comment]
Hi,

Any ideas please?

Thanks

**Comment by daniellee** [comment]
Where did you get the Subscription Id? The Application Id is something else.

In the Azure Portal, navigate to Subscriptions -> Choose subscription -> Overview -> Subscription ID.

**Comment by aquiros17** [comment]
Hi,

Everything it's OK :). The problem was the grafana version included with OMD Labs. I have tested this plugin on Grafana server with the last version (4.5.2) and it works fine.

Thanks!
