### ISSUE TITLE
Results in Log Analytics and Grafana differ

### ISSUE THREAD

**Issue by AliNjie** [grafana/azure-monitor-datasource#82]
I'm having issues, specifically when using the single stat panel, that the results in Log Analytics and Grafana differ from each other.

For example:
I'm running this query in Log Analytics and the "Count" column returns 48:

`WaaSDeploymentStatus
| where UpdateCategory == "Quality" and UpdateReleasedDate >= ago(7d)
| count`

When running the exact same query in Grafana it returns the number 235.

I'm running Grafana 5.4.2 with Azure Monitor Datasource Version 0.3.0.

**Comment by AliNjie** [comment]
I also tried this and set the timepicker to "Last 7 days" and got somewhat same result:
`WaaSDeploymentStatus
| where UpdateCategory == "Quality" and $__timeFilter(UpdateReleasedDate)
| count`

**Comment by daniellee** [comment]
So then I can close this issue?

**Comment by AliNjie** [comment]
I still have issues with this. Example running the same query in Log Analytics and Grafana:

Query:
WaaSUpdateStatus 
| where OSFeatureUpdateStatus == "Not Up-to-date"
| distinct Computer
| count 

**Result in Log Analytics:**
![image](https://user-images.githubusercontent.com/38862494/50153234-25a71d80-02c6-11e9-8b86-1f78af037b1d.png)

**Result in Grafana**
![image](https://user-images.githubusercontent.com/38862494/50153256-2fc91c00-02c6-11e9-8ea8-54a159c6d38a.png)

**Comment by JamesHealey94** [comment]
Make sure you add the
| where $__timeFilter()

**Comment by daniellee** [comment]
The Azure Portal adds a time filter to the where clause automatically. And this plugin does not. It is sort of weird and non-obvious that it does this but maybe this plugin should as well to be consistent.

**Comment by AliNjie** [comment]
You guys we're right. As I added the $__timeFilter() macro, the results in Grafana and Log Analytics matched! Thanks guys.

I agree with you @daniellee. The query method should ideally be identical in both Grafana and Log Analytics.
