### ISSUE TITLE
Log Analytics configuration won't take Azure Monitor credentials.

### ISSUE THREAD

**Issue by awslovato** [grafana/azure-monitor-datasource#85]
The name of this issue changed as I've worked through the issues. Now I get a failure during Save & Test of the datasource configuration. I have the "Same details as Azure Monitor API" selected for Azure Log Analytics API, as that app registration has the correct perms:

![image](https://user-images.githubusercontent.com/22437926/50615286-19fc4f00-0ea1-11e9-98a6-1c2dea1b40af.png)

![image](https://user-images.githubusercontent.com/22437926/50615021-1c11de00-0ea0-11e9-8581-8463b6d8a66a.png)

I created a workspace just for Grafana but it seems I don't even get that far to select it. Any direction would be gratefully appreciated.

Thanks,
James

**Comment by AliNjie** [comment]
Hi!
Try giving the Azure AD Application the "Contributor" role on the Resource Group that the Log Analytics workspace is located in.

The app should inherit permissions on your workspace from the resource group and after a minute or two you should be able to "Save & Test" successfully.

**Comment by awslovato** [comment]
That did the trick, thanks!

![image](https://user-images.githubusercontent.com/22437926/50712173-bce1d400-102d-11e9-9fdc-ab7dde4ab3d6.png)
