### ISSUE TITLE
Q: How do I access pod metrics

### ISSUE THREAD

**Issue by BottlecapDave** [grafana/azure-monitor-datasource#97]
I'm trying to see if I can use Azure Monitor as a viable alternative to Prometheus. I'm trying to plot on a graph the used CPU/memory of each pod within my Kubernetes cluster. 

This information is accessible via the Portal (https://docs.microsoft.com/en-gb/azure/azure-monitor/insights/container-insights-analyze?toc=%2Fazure%2Fmonitoring%2Ftoc.json#view-performance-directly-from-an-aks-cluster) and was wondering if was available via this plugin?

**Comment by SureshKhemka** [comment]
You can use the same plugin for running queries in Log Analytics,  its currently in Preview, I think.
